### ISSUE TITLE
Softlock after loading 2/3 moons

### ISSUE THREAD

**Issue by Entity378** [Badhamknibbs/SCPCB_DunGen_LC#19]
> ~~Apparently after lending and leaving a moon added by the LethalExpansionCore if you try to select and lend on a moon that can spawn the SCPFoundationDungeon the game will softlock.~~

This is the error the console gives when this happens:
![ConsoleERR](https://github.com/Badhamknibbs/SCPCB_DunGen_LC/assets/150670165/a01d1d41-bfb3-4483-bbbe-c3d2b9a3aa54)

While this is what actually happens in the game: you can still move but you can't interact with anything and the seed always remains visible on the screen (loading is infinite)
![Bug](https://github.com/Badhamknibbs/SCPCB_DunGen_LC/assets/150670165/959f7c06-171e-47ec-84a4-d727fe24f0e4)

I tried to check if it was a LethalLevelLoader problem but it doesn't seem to be the case since using the Scoopys Variety Mod dungeon the problem doesn't happen

**Comment by Entity378** [comment]
(I tried to check if it was a LethalLevelLoader problem but it doesn't seem to be the case since using the Scoopys Variety Mod dungeon the problem doesn't happen)

**Comment by Entity378** [comment]
I discovered that apparently lethal expansion has nothing to do with this problem. Trying to put the list of moons RendLevel, DineLevel, TitanLevel and starting the game on each of them in order Rend->Dine->Titan on the third moon that I tried to load (Titan) the error occurred. I'm almost 100% sure that it's a SCPFoundationDungeon mod problem because if I try with other mods that generate custom dungeons (like the Scoopys Variety Mod) this problem doesn't occur.

**Comment by Entity378** [comment]
@Badhamknibbs

**Comment by Entity378** [comment]
@Badhamknibbs apparently the SpringtrapMask mod and SCPFoundationDungeon are incompatible with each other. This incompatibility causes the problem I described above. I don't know what causes the error (I think it's the item name change caused by the SpringtrapMask mod), but I'm 100% sure since I tested your mod individually with every single mod in my modpack for two days.

**Comment by Badhamknibbs** [comment]
> @Badhamknibbs apparently the SpringtrapMask mod and SCPFoundationDungeon are incompatible with each other. This incompatibility causes the problem I described above. I don't know what causes the error (I think it's the item name change caused by the SpringtrapMask mod), but I'm 100% sure since I tested your mod individually with every single mod in my modpack for two days.

Ah, if it's replacing the existing item then it's failing to find the original asset for the mask and crashing when it assumes it can find it; I'll be adding a failsafe to it next patch to avoid that happening.

**Comment by Entity378** [comment]
> > @Badhamknibbs apparently the SpringtrapMask mod and SCPFoundationDungeon are incompatible with each other. This incompatibility causes the problem I described above. I don't know what causes the error (I think it's the item name change caused by the SpringtrapMask mod), but I'm 100% sure since I tested your mod individually with every single mod in my modpack for two days.
> 
> Ah, if it's replacing the existing item then it's failing to find the original asset for the mask and crashing when it assumes it can find it; I'll be adding a failsafe to it next patch to avoid that happening.

I don't actually know if it completely replaces the object or just changes its name.
If you're interested in the piece of code from the SpringtrapMask mod that breaks the mod it's this:
```
((Component)__instance).gameObject.GetComponentInChildren<ScanNodeProperties>().headerText = "Vintage Mascot Head";
((GrabbableObject)__instance).itemProperties.itemName = "Vintage Mascot Head";
```

For now I have published a version of the mod that does not change the name of the mask so you can use it without creating problems.

**Comment by Badhamknibbs** [comment]
I've made an update that'll gracefully fail if it can't find the item (it uses the item name so it won't have conversions but won't crash anymore). Once user/mod defined conversions are added it should be a fairly thing to implement
