### ISSUE TITLE
[bug] config file generation broken since 4.0.0 (incl 4.1.2)

### ISSUE THREAD

**Issue by DravenXD** [Badhamknibbs/SCPCB_DunGen_LC#28]
The config file generates without any options other than Default914Recipes = true
This problem seems to have originated in the 4.0.0 update. The file generates properly in the 3.0.0 version.
![image](https://github.com/Badhamknibbs/SCPCB_DunGen_LC/assets/168028205/9bfe545a-ab10-427f-8534-a17e51280253)

**Temporary fix**: generate the config using an older version (like 3.0.0)
Or paste the following text into the config file:
[SCPCBDunGen.txt](https://github.com/Badhamknibbs/SCPCB_DunGen_LC/files/15284670/SCPCBDunGen.txt)

**Comment by Badhamknibbs** [comment]
The dungeon generation config is handled by LLL from v4 onwards, check the LLL config for customization. The legacy config options won't have any effect on later versions.
